#!/bin/bash

#nasm -f elf helloworld.asm
#ld -m elf_i386 helloworld.o -o helloworld
#gcc -o first first.o driver.c asm_io.o
#/home/sebastian/Dropbox/EAFIT/Organizacion\ de\ computadores/practica2/codigo

#en emacs usar las consolas con ctrl-x-2 para dividir
# alt-x eshell y alt-x term

rm practicaOrg.o
rm practicaOrg
rm practicaOrg.lst
nasm -f elf64 -l practicaOrg.lst practicaOrg.asm
#ld -m elf_i386 practicaOrg.o -o practicaOrg `/usr/include/stdio.h`
#ld -m elf_x86_64 practicaOrg.o -o practicaOrg
gcc -g -nostartfiles -o practicaOrg practicaOrg.o 
./practicaOrg



