#!/bin/bash

#nasm -f elf helloworld.asm
#ld -m elf_i386 helloworld.o -o helloworld
#gcc -o first first.o driver.c asm_io.o
#/home/sebastian/Dropbox/EAFIT/Organizacion\ de\ computadores/practica2/codigo

#en emacs usar las consolas con ctrl-x-2 para dividir
# alt-x eshell y alt-x term

rm variosLlamados.o
rm variosLlamados
rm variosLlamados.lst
nasm -f elf64 -l variosLlamados.lst variosLlamados.s
gcc -c other.c
#ld -m elf_i386 practicaOrg.o -o practicaOrg `/usr/include/stdio.h`
#ld -m elf_x86_64 practicaOrg.o -o practicaOrg
gcc -g -nostartfiles -o variosLlamados variosLlamados.o other.o
./variosLlamados



